#!/usr/bin/env bash
read -p "Please enter project you need to enable deletion protection for an instance: " PROJECTT;
gcloud config set project "$PROJECTT"
while IFS=, read NAME ZONE; do

#gcloud compute instances update "$NAME" --deletion-protection --zone="$ZONE"
FULSE="deletionProtection: false"
CHECK=$(gcloud compute instances describe $NAME --zone=$ZONE --project="$PROJECTT"| grep "deletionProtection")
if [[ "$CHECK" == "$FULSE" ]];
then
	gcloud compute instances update "$NAME" --deletion-protection --zone="$ZONE" --project="$PROJECTT"
	echo "$NAME,Protection,NOW"
else
	echo "$NAME,deletion protection already"
fi

FULSE=0
CHECK=0
done <<< $(gcloud compute instances list --project="$PROJECTT" --sort-by="creationTimestamp" --format="csv[no-heading](name,zone)")